name: Python app CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./app_python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format (Black)
        uses: psf/black@stable
        with:
          options: "--verbose --check"

      - name: Install linter
        run: pip install pylint

      - name: Linter
        run: pylint .

      - name: Tests
        run: pytest src/tests

  docker:
    needs: ci
    environment: ci
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DH_USERNAME }}/${{ vars.DH_IMAGE_NAME_PY }}
          tags: |
            latest
            type=semver,pattern={{major}}.{{minor}}

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          context: app_python

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
